"""Artifact domain model — a unit of produced content of a Run.

A child entity of the Run aggregate root, owned **directly by Run** (DOMAIN_MODEL.md §2.12,
§9.1), carrying provenance to the ``Output`` it was produced from. It is created only via
``Run.create_artifact`` (from an existing Output), is **1:1** with that Output, and is
**immutable except for its own status lifecycle**. There is no aggregate-driving factory here.

This module has no dependency on ``run``/``task``/``output`` (``run`` imports from it), so its
references (``run_id``, ``output_ref``) are plain opaque ``str`` (ADR-0003 §3) — also avoiding an
import cycle.

Scope note (ADR-0006): this is the **minimal faithful subset** of the documented Artifact. The
only wired transition is ``DRAFT -> CANDIDATE``; ``APPROVED``/``REJECTED``/``PUBLISHED`` (need
Human Review) and ``SUPERSEDED`` (needs versioning/rework) are deferred — kept as documented
vocabulary only. ``version`` is always ``1`` while versioning is deferred.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import TypeAlias

ArtifactId: TypeAlias = str
"""Opaque, stable identifier of an Artifact (ADR-0006 §3). Generated by the owning Run."""


class ArtifactStatus(Enum):
    """The six lifecycle states of an Artifact (DOMAIN_MODEL.md §2.12).

    An Artifact is created ``DRAFT``; the only wired transition now is ``DRAFT -> CANDIDATE``
    (ADR-0006 §4). ``APPROVED``/``REJECTED``/``PUBLISHED`` (Human Review) and ``SUPERSEDED``
    (versioning) are documented vocabulary whose edges are deferred.
    """

    DRAFT = "draft"
    CANDIDATE = "candidate"
    APPROVED = "approved"
    REJECTED = "rejected"
    SUPERSEDED = "superseded"
    PUBLISHED = "published"


# --- Read-only snapshot ------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class ArtifactView:
    """Immutable, read-only snapshot of an Artifact (ADR-0006 §2).

    The only representation that leaves the aggregate: no mutable Artifact object is exposed, so
    a child changes only through its Run. A snapshot is point-in-time.
    """

    artifact_id: ArtifactId
    run_id: str
    output_ref: str
    kind: str
    content: str
    version: int
    status: ArtifactStatus


# --- Domain events -----------------------------------------------------------------------
# Recorded in the owning Run's existing event log (ADR-0006 §8).


@dataclass(frozen=True, slots=True)
class ArtifactEvent:
    """Base type for Artifact domain events. Carries the owning Run id and the Artifact id."""

    run_id: str
    artifact_id: str


@dataclass(frozen=True, slots=True)
class ArtifactCreated(ArtifactEvent):
    """Emitted when an Artifact is created from an Output (DOMAIN_MODEL.md §10).

    Carries the provenance (``output_ref``) and the artifact ``kind``.
    """

    output_ref: str
    kind: str


# --- Domain errors -----------------------------------------------------------------------
# Artifact domain-rule violations (ADR-0006 §9). No shared DomainError base is extracted yet
# (rule-of-three follow-up). Actor authorisation reuses Run's UnauthorizedActorError.


class ArtifactDomainError(Exception):
    """Base class for all Artifact domain-rule violations."""


class InvalidArtifactTransitionError(ArtifactDomainError):
    """A requested Artifact status transition is not allowed (ADR-0006 §4)."""


class DuplicateArtifactError(ArtifactDomainError):
    """A second Artifact was requested from an Output that already produced one (1:1)."""


class ArtifactNotApprovedError(ArtifactDomainError):
    """An Artifact was moved to ``APPROVED`` without an approving Human Review (ADR-0007 §6).

    Enforces the invariant "no ``Published`` without ``Approve``" (DOMAIN_MODEL.md §6): the gate
    is checked by the Run root before the transition; the Artifact entity stays unaware of reviews.
    """


class ImmutableArtifactAttributeError(ArtifactDomainError):
    """An attempt was made to change an immutable attribute of an Artifact (everything but status).

    Guards the internal entity for parity with the Task reference implementation. Because Artifact
    is exposed only as an ``ArtifactView`` snapshot, this is a structural defence, not a path
    reachable through the public contract.
    """


# --- Allowed transitions -----------------------------------------------------------------

# Allowed Artifact status transitions (ADR-0006 §4; extended by ADR-0007 §6 with the publication
# path). ``CANDIDATE -> APPROVED`` is additionally gated by the Run (an approving Human Review must
# exist). ``SUPERSEDED`` (versioning) stays deferred — no edges yet.
_ALLOWED_ARTIFACT_TRANSITIONS: dict[ArtifactStatus, set[ArtifactStatus]] = {
    ArtifactStatus.DRAFT: {ArtifactStatus.CANDIDATE},
    ArtifactStatus.CANDIDATE: {ArtifactStatus.APPROVED, ArtifactStatus.REJECTED},
    ArtifactStatus.APPROVED: {ArtifactStatus.PUBLISHED},
    ArtifactStatus.REJECTED: set(),
    ArtifactStatus.SUPERSEDED: set(),
    ArtifactStatus.PUBLISHED: set(),
}

# Immutable public attributes AND their private backing fields: everything except ``status``
# (ADR-0006 §2). Neither a public name nor its backing field may be reassigned after creation.
_IMMUTABLE_ARTIFACT_ATTRIBUTES = frozenset(
    {
        "artifact_id",
        "run_id",
        "output_ref",
        "kind",
        "content",
        "version",
        "_artifact_id",
        "_run_id",
        "_output_ref",
        "_kind",
        "_content",
        "_version",
    }
)


# --- Artifact entity (internal — constructed only by Run) ---------------------------------


class Artifact:
    """The Artifact child entity — a unit of produced content of a Run (ADR-0006 §2).

    **Not** a public API: created only by ``Run.create_artifact`` and mutated (status only) by
    ``Run.transition_artifact``. ``__slots__`` + a guarded ``__setattr__`` make every field but
    ``status`` write-once, mirroring the Task reference implementation.
    """

    __slots__ = (
        "_artifact_id",
        "_content",
        "_kind",
        "_output_ref",
        "_run_id",
        "_status",
        "_version",
    )

    _artifact_id: ArtifactId
    _run_id: str
    _output_ref: str
    _kind: str
    _content: str
    _version: int
    _status: ArtifactStatus

    def __init__(
        self,
        artifact_id: ArtifactId,
        run_id: str,
        output_ref: str,
        kind: str,
        content: str,
        version: int,
    ) -> None:
        # Immutable fields are written exactly once, here, bypassing the guard below.
        object.__setattr__(self, "_artifact_id", artifact_id)
        object.__setattr__(self, "_run_id", run_id)
        object.__setattr__(self, "_output_ref", output_ref)
        object.__setattr__(self, "_kind", kind)
        object.__setattr__(self, "_content", content)
        object.__setattr__(self, "_version", version)
        # The status lifecycle is the only mutable state; it flows through the guarded setter.
        self._status = ArtifactStatus.DRAFT

    def __setattr__(self, name: str, value: object) -> None:
        """Reject reassignment of every attribute except ``status`` (ADR-0006 §2)."""
        if name in _IMMUTABLE_ARTIFACT_ATTRIBUTES:
            raise ImmutableArtifactAttributeError(f"'{name}' is immutable after creation")
        super().__setattr__(name, value)

    @property
    def output_ref(self) -> str:
        """Provenance: the id of the Output this Artifact was produced from."""
        return self._output_ref

    @property
    def view(self) -> ArtifactView:
        """A read-only snapshot of the current state (ADR-0006 §6)."""
        return ArtifactView(
            artifact_id=self._artifact_id,
            run_id=self._run_id,
            output_ref=self._output_ref,
            kind=self._kind,
            content=self._content,
            version=self._version,
            status=self._status,
        )

    def apply_transition(self, to: ArtifactStatus) -> None:
        """Apply a guarded status transition (ADR-0006 §4, §6).

        Only ``DRAFT -> CANDIDATE`` is allowed at this stage; any other edge raises
        ``InvalidArtifactTransitionError`` and leaves the status unchanged.
        """
        if to not in _ALLOWED_ARTIFACT_TRANSITIONS[self._status]:
            raise InvalidArtifactTransitionError(
                f"transition {self._status} -> {to} is not allowed"
            )
        self._status = to
