"""Human Review domain model — the mandatory human decision at the Approval Gate.

A child entity of the Run aggregate root (DOMAIN_MODEL.md §2.14, §9.1): the carrier of the
human's informed decision and its audit. It exists so the architectural invariant holds —
**nothing is published without an explicit human ``Approve``** (PROJECT.md §1, §12). Created and
mutated **only via Run**: the Content Director opens it, the Human Reviewer decides it.

This module depends only on stdlib; its references (``run_id``, ``artifact_ref``) are opaque
``str`` (ADR-0003 §3), avoiding any import cycle.

Scope note (ADR-0007): an audit timestamp is deferred to an injectable clock (ADR-0003 §10);
``CHANGES_REQUESTED`` rework routing and the QA context shown to the reviewer are deferred.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import TypeAlias

ReviewId: TypeAlias = str
"""Opaque, stable identifier of a Human Review (ADR-0007 §4). Generated by the owning Run."""


class ReviewStatus(Enum):
    """The lifecycle states of a Human Review (DOMAIN_MODEL.md §2.14).

    A review is created ``PENDING`` and decided exactly once. ``APPROVED``, ``REJECTED`` and
    ``CHANGES_REQUESTED`` are terminal. Only ``APPROVED`` permits publication (PROJECT.md §12).
    """

    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    CHANGES_REQUESTED = "changes_requested"


# --- Read-only snapshot ------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class HumanReviewView:
    """Immutable, read-only snapshot of a Human Review (ADR-0007 §4).

    The only representation that leaves the aggregate; a review changes only through its Run.
    """

    review_id: ReviewId
    run_id: str
    artifact_ref: str
    status: ReviewStatus
    decided_by: str | None
    reason: str | None


# --- Domain events -----------------------------------------------------------------------
# Recorded in the owning Run's existing event log (ADR-0007 §7).


@dataclass(frozen=True, slots=True)
class HumanReviewEvent:
    """Base type for Human Review domain events. Carries the owning Run id and the review id."""

    run_id: str
    review_id: str


@dataclass(frozen=True, slots=True)
class HumanReviewRequested(HumanReviewEvent):
    """Emitted when a review is opened on a candidate Artifact (DOMAIN_MODEL.md §10)."""

    artifact_ref: str


@dataclass(frozen=True, slots=True)
class HumanReviewApproved(HumanReviewEvent):
    """Emitted when the human decides ``Approve`` (DOMAIN_MODEL.md §10). Carries the author."""

    decided_by: str


@dataclass(frozen=True, slots=True)
class HumanReviewRejected(HumanReviewEvent):
    """Emitted when the human decides ``Reject`` (DOMAIN_MODEL.md §10). Carries author + reason."""

    decided_by: str
    reason: str | None = None


# --- Domain errors -----------------------------------------------------------------------
# No shared DomainError base is extracted yet (rule-of-three follow-up, ADR-0005 §9). Actor
# authorisation reuses Run's UnauthorizedActorError.


class HumanReviewDomainError(Exception):
    """Base class for all Human Review domain-rule violations."""


class InvalidReviewTransitionError(HumanReviewDomainError):
    """A decision was requested on a review that is not ``PENDING`` (already decided)."""


class ImmutableReviewAttributeError(HumanReviewDomainError):
    """An attempt was made to change an immutable attribute of a Human Review.

    Guards the internal entity for parity with the other child entities. Because only a
    ``HumanReviewView`` snapshot leaves the aggregate, this is a structural defence.
    """


# --- Allowed transitions -----------------------------------------------------------------

# A review is decided exactly once: from PENDING to one terminal decision (ADR-0007 §3).
_TERMINAL_DECISIONS: frozenset[ReviewStatus] = frozenset(
    {ReviewStatus.APPROVED, ReviewStatus.REJECTED, ReviewStatus.CHANGES_REQUESTED}
)

_IMMUTABLE_REVIEW_ATTRIBUTES = frozenset(
    {
        "review_id",
        "run_id",
        "artifact_ref",
        "_review_id",
        "_run_id",
        "_artifact_ref",
    }
)


# --- Human Review entity (internal — constructed only by Run) -----------------------------


class HumanReview:
    """The Human Review child entity — one approval decision on a candidate Artifact.

    **Not** a public API: created only by ``Run.open_human_review`` and decided only by
    ``Run.submit_review``. ``__slots__`` + a guarded ``__setattr__`` make identity and the
    review's subject write-once; only the decision (``status`` + ``decided_by`` + ``reason``)
    is set, exactly once.
    """

    __slots__ = (
        "_artifact_ref",
        "_decided_by",
        "_reason",
        "_review_id",
        "_run_id",
        "_status",
    )

    _review_id: ReviewId
    _run_id: str
    _artifact_ref: str
    _status: ReviewStatus
    _decided_by: str | None
    _reason: str | None

    def __init__(self, review_id: ReviewId, run_id: str, artifact_ref: str) -> None:
        object.__setattr__(self, "_review_id", review_id)
        object.__setattr__(self, "_run_id", run_id)
        object.__setattr__(self, "_artifact_ref", artifact_ref)
        self._status = ReviewStatus.PENDING
        self._decided_by = None
        self._reason = None

    def __setattr__(self, name: str, value: object) -> None:
        """Reject reassignment of immutable attributes and their backing fields (ADR-0007 §4)."""
        if name in _IMMUTABLE_REVIEW_ATTRIBUTES:
            raise ImmutableReviewAttributeError(f"'{name}' is immutable after creation")
        super().__setattr__(name, value)

    @property
    def artifact_ref(self) -> str:
        """The candidate Artifact under review (used by Run's approval gate)."""
        return self._artifact_ref

    @property
    def status(self) -> ReviewStatus:
        """The current decision state (used by Run's approval gate)."""
        return self._status

    @property
    def view(self) -> HumanReviewView:
        """A read-only snapshot of the current state (ADR-0007 §4)."""
        return HumanReviewView(
            review_id=self._review_id,
            run_id=self._run_id,
            artifact_ref=self._artifact_ref,
            status=self._status,
            decided_by=self._decided_by,
            reason=self._reason,
        )

    def decide(self, decision: ReviewStatus, decided_by: str, reason: str | None) -> None:
        """Record the human's decision exactly once (ADR-0007 §5).

        ``decision`` must be a terminal outcome and the review must still be ``PENDING``; both
        are validated here. The decision, its author and any reason are recorded immutably.
        """
        if self._status is not ReviewStatus.PENDING:
            raise InvalidReviewTransitionError(f"review {self._review_id} is already decided")
        if decision not in _TERMINAL_DECISIONS:
            raise InvalidReviewTransitionError(f"{decision} is not a valid review decision")
        self._status = decision
        self._decided_by = decided_by
        self._reason = reason
