"""Output domain model — the immutable structured result of a successful Task.

A child entity of the Run aggregate root, owned **through its Task** (DOMAIN_MODEL.md §2.11,
§9.1). It is created only via ``Run.record_output`` after a Task succeeds, is **1:1** with that
Task, and is **immutable** once recorded. There is no aggregate-driving factory here — Run owns
the lifecycle.

This module has no dependency on ``run`` or ``task`` (they import from it), so ``task_id`` is a
plain opaque ``str`` (ADR-0003 §3) — that also avoids an import cycle.

Scope note (ADR-0005): this is the **minimal faithful subset** of the documented Output. Deferred
because they depend on out-of-scope concepts: the validity-validation lifecycle
(``Pending -> Valid/Invalid`` against a Schema) and the ``INVALID`` outcome; QA-oriented metadata
(confidence, risk flags) and rationale; and the produced-``Artifact`` list. Only ``VALID`` is
produced now; ``schema_ref`` is an opaque reference (the Schema entity is deferred).
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import TypeAlias

OutputId: TypeAlias = str
"""Opaque, stable identifier of an Output (ADR-0005 §3). Generated by the owning Run."""


class OutputStatus(Enum):
    """Validity of an Output (DOMAIN_MODEL.md §2.11).

    An Output is created ``VALID`` — the recorded valid result of a successful Task. ``INVALID``
    is documented domain vocabulary, reachable once schema validation exists (deferred, ADR-0005
    §4); it is not produced at this stage.
    """

    VALID = "valid"
    INVALID = "invalid"


@dataclass(frozen=True, slots=True)
class Output:
    """The immutable structured result of one successful Task (ADR-0005 §2, §3).

    Immutable by construction (frozen), so it is safe to expose directly (read-only) through the
    Run root; no snapshot view is needed. ``schema_ref`` is the opaque reference to the contract
    the ``payload`` conforms to (the Schema entity is deferred).
    """

    output_id: OutputId
    task_id: str
    schema_ref: str
    payload: str
    status: OutputStatus


# --- Domain events -----------------------------------------------------------------------
# Recorded in the owning Run's existing event log (ADR-0005 §7).


@dataclass(frozen=True, slots=True)
class OutputEvent:
    """Base type for Output domain events. Carries the owning Run id, Task id and Output id."""

    run_id: str
    task_id: str
    output_id: str


@dataclass(frozen=True, slots=True)
class OutputValidated(OutputEvent):
    """Emitted when an Output is recorded as valid for a succeeded Task (DOMAIN_MODEL.md §10).

    Schema validation itself is deferred (ADR-0005 §4); at this stage the event names a
    successfully produced result being recorded as ``VALID``.
    """


# --- Domain errors -----------------------------------------------------------------------
# Output domain-rule violations (ADR-0005 §8). No shared DomainError base is extracted yet
# (rule-of-three follow-up, ADR-0005 §9). Actor authorisation reuses Run's UnauthorizedActorError.


class OutputDomainError(Exception):
    """Base class for all Output domain-rule violations."""


class InvalidOutputStateError(OutputDomainError):
    """An Output was requested for a Task that has not succeeded (ADR-0005 §5).

    Output exists only as the result of a **successful** Task (DOMAIN_MODEL.md §2.11).
    """


class DuplicateOutputError(OutputDomainError):
    """A second Output was requested for a Task that already has one (1:1, DOMAIN_MODEL.md §5)."""
