"""Task domain model — child Entity of the Run aggregate root.

This module implements the ``Task`` entity exactly as agreed in **ADR-0004 "Task aggregate —
Run↔Task interface contract"**, mirroring the style of the Run reference implementation
(``run.py``). Task is a **child of Run, not its own aggregate root**: it is constructed and
mutated **only through Run** (``Run.open_task`` / ``Run.transition_task``), so this module
exposes **no public standalone factory** — the ``Task`` class is an internal implementation
detail used by ``run.py``. What callers see is the read-only snapshot ``TaskView`` plus the
status / policy / event / error types.

It contains no infrastructure, persistence, serialization, async/threading or integrations
(out of scope; see ``TASK_SPEC.md`` and ``TASK_ACCEPTANCE.md``).

Scenario identifiers in docstrings (e.g. ``THP-01``, ``TRW-02``) refer to `TASK_ACCEPTANCE.md`.

Representation note (per ADR-0003 §3, carried by ADR-0004 §3): identifiers and references the
domain leaves opaque are represented as plain ``str`` — the minimal typing needed, with no
added semantics. ``TaskId`` is a readable alias for such an identifier.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import TypeAlias

from omemo_content_factory.domain.output import (
    DuplicateOutputError,
    InvalidOutputStateError,
    Output,
)

TaskId: TypeAlias = str
"""Opaque, stable identifier of a Task (ADR-0004 §3). Generated by the owning Run."""


class TaskStatus(Enum):
    """The five lifecycle states of a Task (DOMAIN_MODEL.md §2.10; ADR-0004 §2).

    ``SUCCEEDED``, ``FAILED`` and ``SKIPPED`` are the terminal states. ``Retrying`` is **not**
    a separate state — a retry is modelled as a re-entry into ``RUNNING`` that increments the
    attempt counter (ADR-0004 §2; mirrors Run's ``rework_count``).
    """

    PENDING = "pending"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    SKIPPED = "skipped"


@dataclass(frozen=True, slots=True)
class TaskRetryPolicy:
    """Value Object bounding the number of execution attempts (ADR-0004 §6).

    ``max_attempts`` counts every entry into ``RUNNING`` (the first start plus each retry); it
    is a configurable policy value, not a domain rule. The default is ``3`` (mirrors
    ``ReworkPolicy``). Governs scenarios ``TRW-02`` / ``TINV-06``.
    """

    max_attempts: int = 3


# --- Domain events -----------------------------------------------------------------------
# Emitted by a Task on successful transitions (ADR-0004 §7) and recorded in the **owning
# Run's** event log. Verified by TEV-01..TEV-06.


@dataclass(frozen=True, slots=True)
class TaskEvent:
    """Base type for Task domain events. Carries the owning Run id and the Task id."""

    run_id: str
    task_id: str


@dataclass(frozen=True, slots=True)
class TaskCreated(TaskEvent):
    """Emitted when a Task is opened in ``PENDING`` (`TEV-01`; happy path `THP-01`).

    Carries the fixed input references captured at creation (`TID-02`).
    """

    workflow_step_ref: str
    agent_ref: str


@dataclass(frozen=True, slots=True)
class TaskStarted(TaskEvent):
    """Emitted on the first ``PENDING -> RUNNING`` only (`TEV-02`; `THP-02`).

    A retry re-entry to ``RUNNING`` does **not** emit this event (TASK_SPEC.md §7).
    """


@dataclass(frozen=True, slots=True)
class TaskCompleted(TaskEvent):
    """Emitted on reaching ``SUCCEEDED`` (`TEV-03`; `THP-03`)."""


@dataclass(frozen=True, slots=True)
class TaskFailed(TaskEvent):
    """Emitted on reaching ``FAILED`` (`TEV-04`; `TFL-02`). Carries the failure reason."""

    reason: str | None = None


# --- Domain errors -----------------------------------------------------------------------
# Raised on Task domain-rule violations (ADR-0004 §8). Distinct from technical failures. No
# shared DomainError base is extracted yet (rule of three; ADR-0004 §8). Actor authorisation
# reuses Run's ``UnauthorizedActorError`` (ADR-0004 §8), so it is not redefined here.


class TaskDomainError(Exception):
    """Base class for all Task domain-rule violations."""


class InvalidTaskTransitionError(TaskDomainError):
    """A requested Task state transition is not allowed.

    Covers forbidden edges, transitions out of a terminal state and state skips
    (`TFL-01`; invariants `TINV-04`, `TINV-05`).
    """


class TaskRetryLimitExceededError(TaskDomainError):
    """A retry would exceed the configured attempt bound (`TRW-02`; invariant `TINV-06`)."""


class ImmutableTaskAttributeError(TaskDomainError):
    """An attempt was made to change an immutable attribute of a Task (`TINV-02`; `TID-02`).

    Guards the internal entity for parity with the Run reference implementation. Because Task
    is never exposed as a mutable object (only ``TaskView`` snapshots leave the aggregate),
    this is a structural defence, not a path reachable through the public contract.
    """


# --- Read-only snapshot ------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class TaskView:
    """Immutable, read-only snapshot of a Task at a point in time (ADR-0004 §4).

    This is the **only** representation of a Task that leaves the aggregate: no mutable Task
    object is exposed, so a child can never be changed except through its Run (`TAGG-03`).
    A snapshot is point-in-time — it does not track later transitions of the underlying Task.
    """

    task_id: TaskId
    run_id: str
    workflow_step_ref: str
    agent_ref: str
    task_input: str
    status: TaskStatus
    attempt_count: int
    failure_reason: str | None
    output: Output | None


# --- Allowed transitions -----------------------------------------------------------------

# Allowed Task state transitions (TASK_SPEC.md §4; ADR-0004 §5). ``RUNNING -> RUNNING`` is a
# bounded retry. A terminal state has no outgoing edges, so any transition out of it is
# rejected.
_ALLOWED_TASK_TRANSITIONS: dict[TaskStatus, set[TaskStatus]] = {
    TaskStatus.PENDING: {TaskStatus.RUNNING, TaskStatus.SKIPPED},
    TaskStatus.RUNNING: {TaskStatus.RUNNING, TaskStatus.SUCCEEDED, TaskStatus.FAILED},
    TaskStatus.SUCCEEDED: set(),
    TaskStatus.FAILED: set(),
    TaskStatus.SKIPPED: set(),
}

# The terminal Task states (TASK_SPEC.md §4; ADR-0004 §2).
_TERMINAL_TASK_STATES: frozenset[TaskStatus] = frozenset(
    {TaskStatus.SUCCEEDED, TaskStatus.FAILED, TaskStatus.SKIPPED}
)

# Immutable public attributes AND their private backing fields. Neither a public name
# (``task.task_id = ...``) nor its backing field (``task._task_id = ...``) may be reassigned
# after construction (ADR-0004 §3; mirrors Run's guard).
_IMMUTABLE_TASK_ATTRIBUTES = frozenset(
    {
        "task_id",
        "run_id",
        "workflow_step_ref",
        "agent_ref",
        "task_input",
        "_task_id",
        "_run_id",
        "_workflow_step_ref",
        "_agent_ref",
        "_task_input",
    }
)


# --- Task entity (internal — constructed only by Run) -------------------------------------


class Task:
    """The Task child entity — one execution of one Workflow Step inside a Run.

    Concrete implementation of the contract in ADR-0004. **Not** a public API: it has no
    standalone factory and is created only by ``Run.open_task``; it is mutated only by
    ``Run.transition_task``. The Content Director (authorisation) is enforced by Run, the root.

    ``__slots__`` (no instance ``__dict__``) together with a guarded ``__setattr__`` make the
    immutable input fields genuinely write-once, mirroring the Run reference implementation.
    """

    __slots__ = (
        "_agent_ref",
        "_attempt_count",
        "_failure_reason",
        "_output",
        "_retry_policy",
        "_run_id",
        "_status",
        "_task_id",
        "_task_input",
        "_workflow_step_ref",
    )

    _task_id: TaskId
    _run_id: str
    _workflow_step_ref: str
    _agent_ref: str
    _task_input: str
    _retry_policy: TaskRetryPolicy
    _status: TaskStatus
    _attempt_count: int
    _failure_reason: str | None
    _output: Output | None

    def __init__(
        self,
        task_id: TaskId,
        run_id: str,
        workflow_step_ref: str,
        agent_ref: str,
        task_input: str,
        retry_policy: TaskRetryPolicy,
    ) -> None:
        # Immutable inputs are written exactly once, here, bypassing the guard below.
        object.__setattr__(self, "_task_id", task_id)
        object.__setattr__(self, "_run_id", run_id)
        object.__setattr__(self, "_workflow_step_ref", workflow_step_ref)
        object.__setattr__(self, "_agent_ref", agent_ref)
        object.__setattr__(self, "_task_input", task_input)
        # Mutable state is assigned normally and flows through the guarded __setattr__.
        self._retry_policy = retry_policy
        self._status = TaskStatus.PENDING
        self._attempt_count = 0
        self._failure_reason = None
        self._output = None

    def __setattr__(self, name: str, value: object) -> None:
        """Reject reassignment of immutable attributes and their backing fields (`TINV-02`)."""
        if name in _IMMUTABLE_TASK_ATTRIBUTES:
            raise ImmutableTaskAttributeError(f"'{name}' is immutable after creation")
        super().__setattr__(name, value)

    @property
    def is_terminal(self) -> bool:
        """Whether the Task has reached a terminal state (used by Run's completion guard)."""
        return self._status in _TERMINAL_TASK_STATES

    @property
    def output(self) -> Output | None:
        """The owned Output, if any (read-only; used by the root to derive an Artifact)."""
        return self._output

    @property
    def view(self) -> TaskView:
        """A read-only snapshot of the current state (ADR-0004 §4), including any Output."""
        return TaskView(
            task_id=self._task_id,
            run_id=self._run_id,
            workflow_step_ref=self._workflow_step_ref,
            agent_ref=self._agent_ref,
            task_input=self._task_input,
            status=self._status,
            attempt_count=self._attempt_count,
            failure_reason=self._failure_reason,
            output=self._output,
        )

    def attach_output(self, output: Output) -> None:
        """Attach the immutable Output of this Task (called only by Run; ADR-0005 §5, §6).

        Enforced here because the Task owns its own state: the Task must have ``SUCCEEDED``
        (Output exists only for a successful Task) else ``InvalidOutputStateError``, and it must
        not already have an Output (1:1) else ``DuplicateOutputError``.
        """
        if self._status is not TaskStatus.SUCCEEDED:
            raise InvalidOutputStateError(
                f"cannot attach an Output to a Task in {self._status}; it must have SUCCEEDED"
            )
        if self._output is not None:
            raise DuplicateOutputError(f"task {self._task_id} already has an Output")
        self._output = output

    def apply_transition(self, to: TaskStatus, reason: str | None = None) -> TaskEvent | None:
        """Apply a guarded state transition and return its event (or ``None`` if none).

        Enforces the allowed-transitions table (`TFL-01`; `TINV-04`/`TINV-05`) and the attempt
        bound on entry to ``RUNNING`` (`TRW-01`/`TRW-02`; `TINV-06`). Drives the happy path and
        retries (`THP-02`..`THP-04`, `TRW-*`). Authorisation is the Run's responsibility, so it
        is not re-checked here. On a rejected transition the state is left unchanged.
        """
        if to not in _ALLOWED_TASK_TRANSITIONS[self._status]:
            raise InvalidTaskTransitionError(f"transition {self._status} -> {to} is not allowed")
        previous = self._status
        if to is TaskStatus.RUNNING:
            self._register_attempt()
        self._status = to
        if to is TaskStatus.FAILED:
            self._failure_reason = reason
        return self._event_for(previous, to, reason)

    def _register_attempt(self) -> None:
        """Bound attempts by the policy; reject the entry that would exceed it (`TRW-02`)."""
        if self._attempt_count >= self._retry_policy.max_attempts:
            raise TaskRetryLimitExceededError("attempt limit exceeded")
        self._attempt_count += 1

    def _event_for(
        self, previous: TaskStatus, to: TaskStatus, reason: str | None
    ) -> TaskEvent | None:
        """Map a successful edge to its Task event, or ``None`` when the edge emits none.

        A retry (``RUNNING -> RUNNING``) and a skip (``PENDING -> SKIPPED``) emit no event
        (TASK_SPEC.md §7; `TEV-02`, `TEV-05`).
        """
        if to is TaskStatus.RUNNING and previous is TaskStatus.PENDING:
            return TaskStarted(run_id=self._run_id, task_id=self._task_id)
        if to is TaskStatus.SUCCEEDED:
            return TaskCompleted(run_id=self._run_id, task_id=self._task_id)
        if to is TaskStatus.FAILED:
            return TaskFailed(run_id=self._run_id, task_id=self._task_id, reason=reason)
        return None
